# Generated by Django 2.0 on 2022-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SckoolManageSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=50, unique=True)),
                ('edu_group', models.CharField(max_length=50, unique=True)),
                ('period', models.CharField(max_length=50, unique=True)),
                ('tel', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('cover', models.CharField(max_length=50, unique=True)),
                ('remark', models.CharField(max_length=50, unique=True)),
                ('status', models.PositiveSmallIntegerField(unique=True)),
                ('deleted', models.PositiveSmallIntegerField(unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_school',
            },
        ),
    ]
